### ISSUE TITLE
Crashes in Sponge

### ISSUE THREAD

**Issue by BinaryAura** [Mumfrey/LiteLoaderInstaller#8]
Minecraft Crashes when sponge is ran with this.
This is the crash log.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.8-1521-2.1-DEV-739.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 10/19/15 12:44 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalStateException: Sponge was already initialized
  at org.spongepowered.common.Sponge.<init>(Sponge.java:65)
  at org.spongepowered.common.Sponge.class(Sponge.java:50)
  while locating org.spongepowered.common.Sponge

1 error
    at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:339)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:483)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:214)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:413)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalStateException: Sponge was already initialized
  at org.spongepowered.common.Sponge.<init>(Sponge.java:65)
  at org.spongepowered.common.Sponge.class(Sponge.java:50)
  while locating org.spongepowered.common.Sponge

1 error
    at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
    at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
    at org.spongepowered.mod.SpongeMod.<init>(SpongeMod.java:103)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:334)
    ... 11 more
Caused by: java.lang.IllegalStateException: Sponge was already initialized
    at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
    at org.spongepowered.common.Sponge.<init>(Sponge.java:67)
    at org.spongepowered.common.Sponge$$FastClassByGuice$$818cdaf.newInstance(<generated>)
    at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
    at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
    at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
    at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
    at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
    at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
    at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
    at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
    at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
    ... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 406506456 bytes (387 MB) / 578813952 bytes (552 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1521 4 mods loaded, 0 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
        Sponge{1.8-1521-2.1-DEV-739} [SpongeForge] (minecraft.jar) 
        FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1521.jar) 
        Forge{11.14.3.1521} [Minecraft Forge] (forge-1.8-11.14.3.1521.jar) 
    Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.8-1521-2.1-DEV-739.jar)

    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.0' Renderer: 'AMD Radeon HD 7700 Series'
```

**Comment by Mumfrey** [comment]
This is not an issue with the installer.

**Comment by BinaryAura** [comment]
I put an issue on Lite Loaders Git as well.
